### ISSUE TITLE
Не работает на Raspberry Pi (архитектура arm32)

### ISSUE THREAD

**Issue by dvoits** [skytecs/Serilog.Sinks.YandexCloud#2]
При попытке использовать Serilog.Sinks.YandexCloud в рамках сервиса на RPi (архитектура arm32) получаю следующее исключение:
```
System.InvalidOperationException: Unsupported architecture "Unknown".    
at Grpc.Core.Internal.NativeExtension.GetArchitectureString()    
at Grpc.Core.Internal.NativeExtension.GetNativeLibraryFilename()    
at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()    
at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()    
at Grpc.Core.Internal.NativeExtension..ctor()    
at Grpc.Core.Internal.NativeExtension.Get()    
at Grpc.Core.Internal.NativeMethods.Get()    
at Grpc.Core.GrpcEnvironment.GrpcNativeInit()    
at Grpc.Core.GrpcEnvironment..ctor()    
at Grpc.Core.GrpcEnvironment.AddRef()
at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)  
at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials)
at YandexCloud.IamJwtCredentials.IamJwtCredentialsProvider.TokenService()  
at YandexCloud.IamJwtCredentials.IamJwtCredentialsProvider..ctor(String serviceAccountId, String keyId, String pemCertificate)  
at YandexCloud.IamJwtCredentials.IamJwtCredentialsProvider..ctor(IamJwtCredentialsConfiguration configuration)  
at Serilog.Sinks.YandexCloud.YandexCloudLoggerConfigurationExtensions.YandexCloud(LoggerSinkConfiguration sinkConfiguration, String keyId, String serviceAccountId, String privateKey, String folderId, String logGroupId, String resourceId, String resourceType, Int32 batchSizeLimit, Int32 period, Int32 queueLimit, Boolean eagerlyEmitFirstEvent)   
```

На устройстве Rpi установлена Linux raspberrypi 5.10.17-v7+ и .NET 6.0.25.

Сервис, использующий Yandex Cloud sink собирается с помощью команды `dotnet publish -r linux-arm -c Release`.
Версии зависимостей: Serilog 3.1.0, Serilog.Sinks.YandexCloud 1.0.12.

Нашел похожий вопрос на stackoverflow (https://stackoverflow.com/questions/73003589/net-6-grpc-on-raspberry-pi), откуда следует, что 
1. "the problem is that the gRPC is not pure .NET, there is an underlying native library that is not implemented on the Raspberry Pi"
2. "ARM32 is not supported by Grpc.Core by default. You'd need to bring in a custom-build version of the grpc_csharp_ext native component in order to make things work on 32-bit Raspberry pi (and of course it would be officially unsupported). You should be able the run a grpc-dotnet server (ASP.NET Core based) on raspberry pi"

**Comment by code-kot** [comment]
Попробуйте обновить версию `YandexCloud.IamJwtCredentials` до 1.0.2, там уже нет зависимости от `Grpc.Core` только чистый dotnet из `Grpc.Net.Client`.
